name: Prod Build to AWS EC2

on:
  workflow_dispatch:
    inputs:
      description:
        required: false
        description: ''
        type: string

permissions:
  contents: read
  actions: read

env:
  HOST_IP_ADDRESS: 13.209.197.246

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies & Build App
        run: |
          npm ci
          npm run build

      - name: Make Zip
        run: zip -r ./deploy.zip dist package.json package-lock.json ecosystem.config.js scripts
        shell: bash

      - name: Transfer files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_VM_SSH_KEY_V1 }}
          source: ./deploy.zip
          target: '~/app'

      - name: Execute Deploy Commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.HOST_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_VM_SSH_KEY_V1 }}
          port: 22
          script: |
            cd ~/app
            unzip -o deploy.zip
            sudo chmod +x ./scripts/deploy-ec2-v1.sh
            bash ./scripts/deploy-ec2-v1.sh
